### ISSUE TITLE
Réutilisation de hunspell-br 0.15 par LanguageTool

### ISSUE THREAD

**Issue by Wanibzh29** [Drouizig/hunspell-br#1]
Salud deoc'h,
Mat ar jeu emichañs?
Serait-il possible de réutiliser le nouveau "hunspell-br" pour LanguageTool?
https://github.com/languagetool-org/languagetool
A galon
Pêr

**Comment by Denez** [comment]
Salut Pierre, 
Bien sûr, la licence le permet sans avoir besoin de demander :-)
Dominiko l'utilisait déjà pour le contrôle de l'orthographe m'avait-il semblé.
La base Hunspell n'étant pas assez typée pour une utilisation grammaticale.
Une version 0.16 est en travail...
N'hésite pas à dire s'il manque des mots, ou s'il se trouve des coquilles.

Salutations
Denis
