### ISSUE TITLE
Coquille(s) trouvée(s)

### ISSUE THREAD

**Issue by Wanibzh29** [Drouizig/hunspell-br#2]
Salud deoc'h,
Mat ar jeu emichañs,
Je viens de voir qu'il y avait potentiellement une coquille pour le mot "daeren" qui est attesté dans le dictionnaire "An Here" et dans le dictionnaire de l'Ofis 'Meurgorf' sous la form "daerenn".
Peut-être que la discussion peut rester ouverte au cas où ?
A galon
Pêr

**Comment by Denez** [comment]
Fixed in 0.16; Thanks for report !
