### ISSUE TITLE
Problème de én à la place de "ñ"

### ISSUE THREAD

**Issue by Wanibzh29** [Drouizig/hunspell-br#4]
Salud tudoù,
J'ai remarqué qu'Hunspell n'était pas à même de corriger l'emploi fautif de "én" à la place de "ñ" lorsqu'on utilise Windows, comment pourrait-on faire pour régler ce problème a votre avis ? (si ce n'est passé à Linux bien évidemment ^^).
Par exemple quand je me trompes et que j'écris "bremaén" il me propose "bremana".
Pêr

**Comment by Wanibzh29** [comment]
Salud tudoù,
Penaos eo?
Bloavezh mat, yec'hed mat ha prosperite.
J'ai remarqué une petite erreur mais je ne suis pas bien sûr de la cerner.
Alors je vais montrer un petit exemple:
J'ai écrit l'autre jour "An arouez-maén" et Hspll m'à proposé "arouezenn" à la place. 
Sinon j'ai essayé avec "Al lizher-maén" et ça m'à corrigé en "lizherañ".
Pensez-vous pouvoir fixer ce genre de problème ?
A galon
Pêr

**Comment by Denez** [comment]
Fixed in 0.16. Thanks for report.
