### ISSUE TITLE
Ne vez kinniget alies ar stumm gant "ñ" pa vez ur fazi

### ISSUE THREAD

**Issue by soig** [Drouizig/hunspell-br#5]
Salud deoc'h.
Siwazh, alies-mat ne vez kinniget alies ar stumm gant "ñ" pa vez ur fazi.
Da skouer e Firefox:
eman --> emaon... [KO]
breman --> brenan .... [KO]
sonj --> son, sonje, ... [KO] met:
sonjal -> soñjal ... [MAT]
N'eus nemet evit "anezhan" hag evit un nebeut gerioù all e vez kinniget ar stumm "anezhañ"

**Comment by Denez** [comment]
Fixed in 0.16. Thanks for report.
